title: Revan Parimi
description: Software Developer by profession, love to code adn create algorithms
logo : /assets/images/Self.jpg
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
